### ISSUE TITLE
Error when running ov-client on macOS

### ISSUE THREAD

**Issue by delude88** [gisogrimm/ov-client#23]
When installing the ov-client on macOS and running it, the box.orlandoviols.com website reports the following error:

_Device error:
Unable to open receiver module "ortf": dlopen(ovclienttascarreceiver_ortf.dylib, 2): image not found_

This seems like a broken library dependency.

**Comment by delude88** [comment]
Ok, running ov-client as sudo seems to fix the issue.

Background: on many unix systems the lower ports (9871) cannot be reserved without root privileges.

Shall we use another port or just require the user to have root privileges / run it as sudo?

**Comment by gisogrimm** [comment]
What is the threshold for user space ports? On Linux it is 1024.

Regarding the dlopen problem: ovclienttascarreceiver_ortf.dylib (and similar ..._hrtf.dylib) are the dynamic libraries which are needed to render the sound. They are compiled as part of ov-client and will be at
ov-client/tascar/plugins/build/.

**Comment by gisogrimm** [comment]
on Linux, running it with
`LD_LIBRARY_PATH=./tascar/plugins/build/ ./build/ov-client`
should solve the library issue.

**Comment by hendrikkayser** [comment]
> `LD_LIBRARY_PATH=./tascar/plugins/build/ ./build/ov-client`

I can confirm that this solves the issue under macos (without sudo).

**Comment by alessandrostone** [comment]
Yep That works 👍

**Comment by delude88** [comment]
Ok works for me too.

Maybe we could later provide a shell script for this ... but I'll close this issue, since we got this workaround 👍
